title: Machine Learning @ Jetzt Gov

titles_from_headings:
  enabled: true
  strip_title: true
  
remote_theme: jekyll/minima
minima:
  skin: solarized

author:
  name: Saqib Ali
  date_format: "On day %-j of the year %Y which fell in the week %-W of in the month of %B. Or simply %A, %B %-d, %Y"
